[package]
name = "sp-cli"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "start-page"
path = "src/main.rs"

[dependencies]
clap.workspace = true
anyhow.workspace = true
sp-config.workspace = true
sp-tui-host.workspace = true
sp-server.workspace = true
